<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View $block  */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty" id="product_addtocart_form" data-bind="scope:'qty-counter'" >
            <div class="control counter">
                <div tabindex="0" class="counter__changer counter__changer-minus" >
                    <span>-</span>
                </div>
                <input type="text"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty counter__input"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       data-bind="value: counterValue()"
                       />
                <div tabindex="0"  class="counter__changer counter__changer-plus" data-bind="click: increment" >
                    <span>+</span>
                </div>
            </div>
            <?php if($_product->isInStock()): ?>
            <div class="stock">
                <img class="stock__image" src="<?= $block->getViewFileUrl('Magento_Catalog::images/check-mark.svg')?>" alt="check mark" />
                <p class="stock__text">  in stock</p>
                <span class="stock__qty"> <?= $_product->getExtensionAttributes()->getStockItem()->getQty() ?> items available</span>
            </div>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
        "Magento_Ui/js/core/app": {
           "components": {
                "qty-counter": {
                    "component": "qty-counter",
                    "config": {
                        "counterValue": 0
                    }
                }
            }
        }
        }
    }
</script>
