<?php

/** @var \Magento\Catalog\Block\Product\View\Attributes $block  */

/**
 * @var Magento\Catalog\Helper\Output
 */
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
$product = $block->getProduct();
$attributes = $block->getAdditionalData();

$customAttributes = [ 'size' => [ 'label' => 'Dimension:', 'code' => 'size'], 'code' => [ 'label' => 'Colour:', 'code' => 'color'], 'material' => [ 'label' => 'Material:', 'code' => 'material']];
$count = count($customAttributes);

?>
<?php if(count($attributes) > 0): ?>
        <div class="attributes__container">
            <ul>
                <?php foreach($customAttributes as $customAttribute): ?>

                    <?php
                        $attributeText= $product->getAttributeText($customAttribute['code']);
                        if($attributeText): ?>
                            <li class="attributes__item">
                                <span class="attributes__title"><?= $customAttribute['label'] ?></span>
                                <?php
                                 if(is_array($attributeText)) $attributeText = implode(', ', $attributeText)
                                 ?>
                                 <p class="attributes__text"><?= $attributeText ?></p>
                            </li>
                        <?php $count--; ?>
                        <?php endif; ?>

                <?php endforeach; ?>

                <?php if($count !== 0): ?>

                        <?php foreach($attributes as $attribute): ?>
                            <?php if($count === 0) break ?>
                            <?php if(!in_array($attribute['code'], $customAttributes)): ?>
                                <li class="attributes__item">
                                    <span class="attributes__title"><?= $attribute['label'] ?></span>
                                    <p class="attributes__text"><?= $attribute['value'] ?></p>
                                </li>
                                <?php $count-- ?>
                            <?php endif; ?>

                        <?php  endforeach; ?>
                <?php endif; ?>
            </ul>
    </div>
<?php endif; ?>
